### ISSUE TITLE
Main.R hours to seconds

### ISSUE THREAD

**Issue by ImmoShan** [eap-fes-unigoe/canopy-model#4]
We noticed a possible error in Main.R in the conversion from hours to seconds.

# Setting some time unit variables in unit seconds
**shour  <- 3800**
shalfh <- shour/2
sday   <- shour * 24
smonth <- sday * 30
syear  <- sday * 365
dt     <- shour

Shouldn't shour be 3600?

**Comment by femoyano** [comment]
You are quite right :)
